# Generated by Django 5.2.6 on 2025-09-12 19:16

import django.db.models.deletion
import verification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('document_type', models.CharField(max_length=50)),
                ('doc_file', models.FileField(upload_to='documents/', validators=[verification.models.validate_file_extension])),
                ('selfie_file', models.ImageField(upload_to='selfies/', validators=[verification.models.validate_file_extension])),
                ('verified', models.BooleanField(default=False)),
                ('verification_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
