# Generated by Django 5.2.6 on 2025-09-12 20:23

import verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to=verification.models.user_directory_path, validators=[verification.models.validate_file_extension, verification.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='document',
            name='selfie_file',
            field=models.ImageField(upload_to=verification.models.user_directory_path, validators=[verification.models.validate_file_extension, verification.models.validate_file_size]),
        ),
    ]
