# Generated by Django 6.0.3 on 2026-04-18 21:06

import verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_document_doc_file_alter_document_selfie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to=verification.models.document_upload_path, validators=[verification.models.validate_file_extension, verification.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='selfie_file',
            field=models.FileField(upload_to=verification.models.selfie_upload_path, validators=[verification.models.validate_file_extension, verification.models.validate_file_size]),
        ),
    ]
