# Generated by Django 6.0.3 on 2026-05-12 23:23

import verification.models
import verification.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_add_callback_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='callback_url',
            field=models.URLField(blank=True, null=True, validators=[verification.validators.validate_no_ssrf]),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to=verification.models.document_upload_path, validators=[verification.models.validate_file_extension, verification.models.validate_file_size, verification.validators.validate_file_content]),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('id_card', 'National ID card'), ('driver_license', "Driver's license"), ('residence_permit', 'Residence permit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='selfie_file',
            field=models.FileField(upload_to=verification.models.selfie_upload_path, validators=[verification.models.validate_file_extension, verification.models.validate_file_size, verification.validators.validate_file_content]),
        ),
    ]
